---
title: "explore-data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
```

```{r}
MA_SAT_18_19 <- read_excel("sat_performance.xlsx", 
                        col_types = c("text", "numeric",
                                      "numeric", "numeric",
                                      "logical", "numeric"),
                        skip = 1) %>% 
  clean_names()

MA_PPE_18 <- read_excel("PerPupilExpenditures.xlsx",
                        col_types = c("text", "numeric",
                                      "numeric", "text",
                                      "text", "text",
                                      "text", "text",
                                      "logical"),
                        skip = 1) %>% 
  clean_names() %>% 
  select(-x9)

mass_staff_demographics <- read_excel("staffracegender.xlsx",
                                      skip = 1) %>% 
  View()

mass_salaries <- read_excel("TeacherSalaries.xlsx")
```

```{r}
mass_joined <- MA_SAT_18_19 %>% 
  full_join(MA_PPE_18, by = c("district_name" = "district_name",
                              "district_code" = "district_code"))
```

```{r}
mass_joined %>% 
  arrange(desc(in_district_expenditures)) %>% 
  View()
```


```{r}
mass_joined %>% 
  filter(district_name == "Andover") %>% 
  summary()
```
 
